services:
  flights_sql_server:
    image: mysql:8.0
    container_name: flights_sql_server
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: schiphol
    ports:
      - 3306:3306
    volumes:
      - flights_data:/var/lib/mysql
      - ./pages/schiphol/flights_mysql_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: --secure-file-priv=/docker-entrypoint-initdb.d

  main:
    build: .
    ports:
      - 5000:5000
    depends_on:
      flights_sql_server:
        condition: service_healthy

  airflow_sql_server:
    image: mysql:8.0
    container_name: airflow_sql_server
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - airflow_data:/var/lib/mysql
      - ./pages/schiphol/airflow_mysql_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: 
      - --explicit_defaults_for_timestamp=1
      - --sort_buffer_size=8M

  airflow:
    build: ./pages/schiphol
    container_name: airflow
    ports:
      - 8080:8080
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqldb://airflow:airflow@airflow_sql_server/airflow
    volumes:
      - ./pages/schiphol/airflow/dags:/opt/airflow/dags
      - ./pages/schiphol/etl:/opt/airflow/etl
    depends_on:
      airflow_sql_server:
        condition: service_healthy
      flights_sql_server:
        condition: service_healthy  
    command: bash -c "airflow db migrate && airflow standalone"

volumes:
  flights_data:
  airflow_data:
